language: node_js # 指定语言环境
sudo: required # 是否需要 sudo 权限
node_js:
  - "8" # 指定 NodeJS 版本

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
    - hexo

before_install:
  - echo "Hexo environment pre install start."
  - echo 'system info:'
  - uname -a
  - echo 'nodejs version:'
  - node --version
  - echo 'npm version:'
  - npm --version
  - npm install -g hexo-cli

# S: Build Lifecycle

install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install
  - npm install hexo-deployer-git --save
#  - source travis_env_init.sh # 指定 shell 脚本文件来做初始化
  - echo "hexo and packages install complete."

before_script:
#  - npm install -g gulp

script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean 
  - hexo generate # Hexo 常规命令，执行清理和生成

after_script:
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
#  - sed -i "s/GIT_REPO_TOKEN/${GIT_REPO_TOKEN}/g" ./_config.yml
  - sed -i "s~git@github.com:~https://${GIT_REPO_TOKEN}@github.com/~" _config.yml
  - cat ./_config.yml
#  - hexo deploy

after_success: # 在构建成功后要运行的命令，构建失败不会执行，其他同上
#  - hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客
  - hexo deploy

# E: Build LifeCycle

notifications: # 设置通知项
  email: true
